### ISSUE TITLE
MAJOR bug where everyone has the same face

### ISSUE THREAD

**Issue by Lady-Luck** [Killface1980/RW_FacialStuff#18] opened 2017-01-10 01:23 UTC
Including this weird one that has two hairstyles at once.

http://i.imgur.com/p7wG2oI.png

Colonist Bar is correct, btw, the pawns actually do look like that.

**Comment by Lady-Luck** [comment] 2017-01-10 01:39
Oh shit, this is affecting the release version on Steam Workshop too.

**Comment by Lady-Luck** [comment] 2017-01-10 01:43
The good news is this only seems to happen on new games, and even then you can save and restart the game and the faces will be fixed.

**Comment by Killface1980** [comment] 2017-01-10 15:34
Weird, will take care of it later. Thank you for reproducing & reporting.

**Comment by Lady-Luck** [comment] 2017-06-09 22:13
This only started happening to me again in A17 after using Verify Start to generate pawns. Doesn't occur without both Facial Stuff and Verify Start enabled.

Worse yet, it seems save and restart doesn't totally fix the faces anymore. They're ending up with skin color and facial hair that they shouldn't. Women with beards!

The good news is Verify Start actually has a source now if you want to pick through it and see what's going on: https://github.com/scuba156/VerifyStartA17/tree/master/VerifyStartA17/Source

**Comment by Killface1980** [comment] 2017-06-10 06:49
I'll add a note that Verify Start has issues with this mod.
FS is just not meant to generate 100s of faces in mere seconds, I can't just use layers like the apparel. Each pixel of each face gets placed, meaning 128x128x3 = 49,152 pixels have to be set - for each layer (1x head, 1x eye etc.)
Maybe the author of Verify Start has a solution to circumvent the portrait if a pawn is not fit. Sorry to say, but until I could use layers like all the other stuff in RW, this can't be fixed by me.

**Comment by Lady-Luck** [comment] 2017-06-10 20:44
I've actually already contacted the author about that, but bear in mind he is not the original programmer of the mod and instead ported it over to A17 and made it compatible with Prepare Carefully. I honestly feel bad even asking, but it's certainly something that is desperately needed.

Do you have any insight on how to accomplish pawn generation without rendering the pawn?

**Comment by Killface1980** [comment] 2017-06-11 10:33
nay, not really. generation is not the problem here. the PawnRenderer initializes the graphics, calling a method named ResolveAllGraphics. this is where my mod comes into play. it checks if the pawn is human, and returns a new head texture. I don't know how to turn that off only in VerifyStart, thus I guess the best bet would be that Verify Start deactivates the PawnRenderer/rendering of the portrait if the created pawn isn't suitable anyways. Would also speed up the generation process without Facial Stuff active.

**Comment by Lady-Luck** [comment] 2017-06-12 01:18
Been looking into these, even asked Zorba and Fluffy, but this looks like one hell of a thing to try and do. Rendering is nested so very deep in pawn generation.

**Comment by Killface1980** [comment] 2017-06-12 07:57
That's not exactly what I meant. The renderer is only active if it is invoked. My mod only adds faces if the renderer asks for a graphic set. 
Every time VS or PC draw the pawn's image, my mod is started. I'm sure, Verify start can check the skills without showing the pawn, thus not invoking the graphic set at all.

**Comment by Killface1980** [comment] 2017-06-13 18:20
Update, I was able to use the PawnRenderer for making faces as originally intended :)
The new branch doesn't create textures on the fly any more, thus much faster and less RAM consuming. https://github.com/Killface1980/RW_FacialStuff/tree/PawnRenderer haven't tested it properly yet.

**Comment by Lady-Luck** [comment] 2017-06-13 20:26
Awesome, I'll test it out very soon!

**Comment by Killface1980** [comment] 2017-06-14 01:09
closed, as only possible bug in pre-render version

**Closed by Killface1980** 2017-06-14 01:09 UTC
Labels: bug
